service: alexa-skill

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  stage: ${opt:stage, 'dev'}
  role: ${ssm:/cssapps/server/role}

functions:
  emergencyHandler:
    handler: index.emergencyHandler
    events:
      - alexaSkill: ${ssm:/cssapps/alexa/emergency}
  helloHandler:
    handler: index.helloHandler
    events:
      - alexaSkill: ${ssm:/cssapps/alexa/general}
      - http:
          path: mutebot/hello
          method: get

plugins:
  - serverless-offline
